version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=phpmyadmin
    volumes:
      - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:5.2.1-fpm
    container_name: phpmyadmin
    restart: unless-stopped
    env_file: .env
    environment:
      - PHPMYADMIN_DB_HOST=db:3306
      - PHPMYADMIN_DB_USER=$MYSQL_USER
      - PHPMYADMIN_DB_PASSWORD=$MYSQL_PASSWORD
      - PHPMYADMIN_DB_NAME=phpmyadmin
    volumes:
      - phpmyadmin:/var/www/html
    networks:
      - app-network

  webserver:
    depends_on:
      - phpmyadmin
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - phpmyadmin:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
volumes:
  phpmyadmin:
  dbdata:

networks:
  app-network:
    driver: bridge
